name: Automatic Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3

      - name: Zip Dosyası Oluştur
        run: zip -r rose-temp.zip . -x "*.git*"

      - name: Release Oluştur ve Zip'i Yükle
        uses: softprops/action-gh-release@v2
        with:
          files: rose-temp.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
